services:
  - type: web
    name: clv-backend
    env: ubuntu
    region: oregon
    buildCommand: |
      apt-get update
      apt-get install -y build-essential cmake pkg-config libssl-dev libsasl2-dev
      cd /tmp
      wget https://github.com/mongodb/mongo-cxx-driver/releases/download/r3.8.1/mongo-cxx-driver-r3.8.1.tar.gz
      tar -xzf mongo-cxx-driver-r3.8.1.tar.gz
      cd mongo-cxx-driver-r3.8.1/build
      cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DBSONCXX_POLY_USE_BOOST=1 \
          -DCMAKE_CXX_STANDARD=17
      make -j$(nproc)
      make install
      cd /opt/render/project/src/Backend
      make clean
      make clv-server
    startCommand: ./Backend/clv-server
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://rizxx50_db_user:P3VywhlQkN49ZWIf@clv.llk5c76.mongodb.net/CLV_Calculator?retryWrites=true&w=majority
      - key: MONGODB_DB_NAME
        value: CLV_Calculator
      - key: ALLOWED_ORIGINS
        value: "*"
    plan: free
    autoDeploy: true